### ISSUE TITLE
Need release compatible with Jekyll 4.3.3

### ISSUE THREAD

**Issue by dubinsky** [wikibonsai/jekyll-wikirefs#1]
Hi @manunamz!
I'd love to try this plugin, but it does not work for me with the current Jekyll...
Are there any plans to release an update?
Thank you!

**Comment by manunamz** [comment]
Dependency requirements have been [loosened](https://github.com/wikibonsai/jekyll-wikirefs/commit/a79de870476ce2e948614dc32df8bbbb8fb48ad6#diff-d7fb1cfc807b5928a5b1f566bcd9afbe0839e6b4aed925dd45d0f56a212f5b7f) in [v0.0.15](https://github.com/wikibonsai/jekyll-wikirefs/releases/tag/v0.0.15).

**Comment by dubinsky** [comment]
Thank you!!
